// Generated by Melange

import * as React from "react";
import * as SuspensionLoader from "./components/SuspensionLoader.js";
import * as RescriptReactRouter from "@rescript/react/./src/RescriptReactRouter.js";

function App(Props) {
  var lazyHome = React.createElement(React.lazy(function (param) {
            var __x = import("./pages/Home.js");
            return __x.then(function (comp) {
                        return Promise.resolve({
                                    default: comp.make
                                  });
                      });
          }), undefined);
  var lazyAbout = React.createElement(React.lazy(function (param) {
            var __x = import("./pages/About.js");
            return __x.then(function (comp) {
                        return Promise.resolve({
                                    default: comp.make
                                  });
                      });
          }), undefined);
  var url = RescriptReactRouter.useUrl(undefined, undefined);
  var match = url.path;
  var component = match ? (
      match.hd === "about" && !match.tl ? React.createElement(SuspensionLoader.make, {
              children: lazyAbout
            }) : React.createElement("div", undefined)
    ) : React.createElement(SuspensionLoader.make, {
          children: lazyHome
        });
  return React.createElement("div", {
              className: "flex flex-col"
            }, component);
}

var make = App;

export {
  make ,
}
/* react Not a pure module */
